resources:
  - ../base

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: mono-controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --log-level=debug