apiVersion: minio.f110.dev/v1alpha1
kind: MinIOBucket
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: minio
  policy: readOnly
  createIndexFile: true
---
apiVersion: minio.f110.dev/v1alpha1
kind: MinIOBucket
metadata:
  name: test2
spec:
  selector:
    matchLabels:
      app: minio