apiVersion: minio.f110.dev/v1alpha1
kind: MinIOCluster
metadata:
  name: test-cluster
  labels:
    app: minio
spec:
  image: minio/minio:RELEASE.2024-04-18T19-09-19Z
  nodes: 1
  totalSize: 10
  identityProvider:
    clientId: "306238040135762435"
    clientSecretRef:
      name: client-secret
      key: clientSecret
    discoveryUrl: "https://login.f110.dev/.well-known/openid-configuration"
    scopes: ["oidc", "email"]
  externalUrl: http://127.0.0.1:8080
  buckets:
    - name: foo
      policy: Public
      createIndexFile: true
    - name: bar
---
apiVersion: v1
kind: Secret
metadata:
  name: client-secret
stringData:
  clientSecret: "ttbKIRvJilXRCpZmbjdlnNyb0bV6NZ6fGVrWlLkaxObLALaITWFhc0GofnzR7jId"
