
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: harbor-project-operator
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - pods
  - services
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - pods/portforward
  verbs:
  - create
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - harbor.f110.dev
  resources:
  - harborprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.f110.dev
  resources:
  - harborprojects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - harbor.f110.dev
  resources:
  - harborrobotaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.f110.dev
  resources:
  - harborrobotaccounts/status
  verbs:
  - get
  - patch
  - update
