apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-extra-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-extra-operator
  labels:
    controllers: minio-extra-operator
spec:
  selector:
    matchLabels:
      controllers: minio-extra-operator
  replicas: 1
  template:
    metadata:
      labels:
        controllers: minio-extra-operator
    spec:
      serviceAccountName: minio-extra-operator
      containers:
        - name: operator
          image: quay.io/f110/minio-extra-operator@sha256:d72e8ac7d6491520fce6c191f3fb031a633baaa7158e4b0f650ca4f4a753684c
          args:
            - "-lease-lock-name=minio-extra-operator"
            - "-lease-lock-namespace=$(MY_NAMESPACE)"
            - "-v=4"
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
