/*
MIT License

Copyright (c) 2020 Fumihiro Ito

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/f110/tools/controllers/minio-extra-operator/pkg/api/minio/v1alpha1"
	scheme "github.com/f110/tools/controllers/minio-extra-operator/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MinIOBucketsGetter has a method to return a MinIOBucketInterface.
// A group's client should implement this interface.
type MinIOBucketsGetter interface {
	MinIOBuckets(namespace string) MinIOBucketInterface
}

// MinIOBucketInterface has methods to work with MinIOBucket resources.
type MinIOBucketInterface interface {
	Create(*v1alpha1.MinIOBucket) (*v1alpha1.MinIOBucket, error)
	Update(*v1alpha1.MinIOBucket) (*v1alpha1.MinIOBucket, error)
	UpdateStatus(*v1alpha1.MinIOBucket) (*v1alpha1.MinIOBucket, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MinIOBucket, error)
	List(opts v1.ListOptions) (*v1alpha1.MinIOBucketList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MinIOBucket, err error)
	MinIOBucketExpansion
}

// minIOBuckets implements MinIOBucketInterface
type minIOBuckets struct {
	client rest.Interface
	ns     string
}

// newMinIOBuckets returns a MinIOBuckets
func newMinIOBuckets(c *MinioV1alpha1Client, namespace string) *minIOBuckets {
	return &minIOBuckets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the minIOBucket, and returns the corresponding minIOBucket object, and an error if there is any.
func (c *minIOBuckets) Get(name string, options v1.GetOptions) (result *v1alpha1.MinIOBucket, err error) {
	result = &v1alpha1.MinIOBucket{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("miniobuckets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MinIOBuckets that match those selectors.
func (c *minIOBuckets) List(opts v1.ListOptions) (result *v1alpha1.MinIOBucketList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MinIOBucketList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("miniobuckets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested minIOBuckets.
func (c *minIOBuckets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("miniobuckets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a minIOBucket and creates it.  Returns the server's representation of the minIOBucket, and an error, if there is any.
func (c *minIOBuckets) Create(minIOBucket *v1alpha1.MinIOBucket) (result *v1alpha1.MinIOBucket, err error) {
	result = &v1alpha1.MinIOBucket{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("miniobuckets").
		Body(minIOBucket).
		Do().
		Into(result)
	return
}

// Update takes the representation of a minIOBucket and updates it. Returns the server's representation of the minIOBucket, and an error, if there is any.
func (c *minIOBuckets) Update(minIOBucket *v1alpha1.MinIOBucket) (result *v1alpha1.MinIOBucket, err error) {
	result = &v1alpha1.MinIOBucket{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("miniobuckets").
		Name(minIOBucket.Name).
		Body(minIOBucket).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *minIOBuckets) UpdateStatus(minIOBucket *v1alpha1.MinIOBucket) (result *v1alpha1.MinIOBucket, err error) {
	result = &v1alpha1.MinIOBucket{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("miniobuckets").
		Name(minIOBucket.Name).
		SubResource("status").
		Body(minIOBucket).
		Do().
		Into(result)
	return
}

// Delete takes name of the minIOBucket and deletes it. Returns an error if one occurs.
func (c *minIOBuckets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("miniobuckets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *minIOBuckets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("miniobuckets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched minIOBucket.
func (c *minIOBuckets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MinIOBucket, err error) {
	result = &v1alpha1.MinIOBucket{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("miniobuckets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
