apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor
  namespace: harbor
data:
  EXT_ENDPOINT: http://registry.f110.dev
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: harbor
stringData:
  HARBOR_ADMIN_PASSWORD: foobar
---
apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: harbor
spec:
  selector:
    app.kubernetes.io/name: harbor
  ports:
    - port: 80
      protocol: TCP