apiVersion: v1
kind: ServiceAccount
metadata:
  name: mono-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-controller-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mono-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mono-controller-manager
    spec:
      serviceAccountName: mono-controller-manager
      containers:
        - name: controller
          image: registry.f110.dev/tools/controller-manager:latest
          imagePullPolicy: IfNotPresent
          args:
            - --lease-lock-name=mono-controller-manager
            - --lease-lock-namespace=$(MY_NAMESPACE)
            - --cluster-domain=cluster.local
            - --harbor-namespace=harbor
            - --harbor-service-name=harbor
            - --admin-secret-name=harbor
            - --core-configmap-name=harbor
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: metrics
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /liveness
          readinessProbe:
            httpGet:
              port: 8080
              path: /readiness
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 30m
              memory: 32Mi
      terminationGracePeriodSeconds: 10
