
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: grafana-admin
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.f110.dev
  resources:
  - grafanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.f110.dev
  resources:
  - grafanas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - grafana.f110.dev
  resources:
  - grafanausers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.f110.dev
  resources:
  - grafanausers/status
  verbs:
  - get
  - patch
  - update
