apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-extra-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: minio-extra-operator
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  - secrets
  - services
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - pods/portforward
  verbs:
  - create
  - get
  - list
- apiGroups:
  - minio.f110.dev
  resources:
  - miniobuckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.f110.dev
  resources:
  - miniobuckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - miniocontroller.min.io
  resources:
  - minioinstances
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: minio-extra-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-extra-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-extra-operator
subjects:
- kind: ServiceAccount
  name: minio-extra-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    controllers: minio-extra-operator
  name: minio-extra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      controllers: minio-extra-operator
  template:
    metadata:
      labels:
        controllers: minio-extra-operator
    spec:
      containers:
      - args:
        - -lease-lock-name=minio-extra-operator
        - -lease-lock-namespace=$(MY_NAMESPACE)
        - -v=4
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/f110/minio-extra-operator@sha256:3664832ebcc4a8e81c128f8afd74684b9c09c6ed62dc43b8722bccb665e0a159
        name: operator
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: minio-extra-operator
      terminationGracePeriodSeconds: 10
