package macports

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestOutput(t *testing.T) {
	tokens := []*PortfileToken{
		{
			Type:  PortfileTokenComment,
			Value: "# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4",
		},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "PortSystem"},
		{Type: PortfileTokenIdent, Value: "1.0", StartPos: 11},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "PortGroup"},
		{Type: PortfileTokenIdent, Value: "golang 1.0", StartPos: 11},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "go.setup"},
		{Type: PortfileTokenIdent, Value: "github.com/kubecfg/kubecfg 0.26.0 v", StartPos: 11},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "revision"},
		{Type: PortfileTokenIdent, Value: "0", StartPos: 11},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "name"},
		{Type: PortfileTokenIdent, Value: "kubecfg", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "homepage"},
		{Type: PortfileTokenIdent, Value: "https://github.com/kubecfg/kubecfg", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "description"},
		{Type: PortfileTokenIdent, Value: "A tool for managing complex enterprise Kubernetes environments as code.", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "long_description"},
		{Type: PortfileTokenIdent, StartPos: 17, Value: "kubecfg allows you to express the patterns across your infrastructure and \\"},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, StartPos: 4, Value: "reuse these powerful \"templates\" across many services, and then manage those templates \\"},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, StartPos: 4, Value: "as files in version control. The more complex your infrastructure is, the more you will \\"},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, StartPos: 4, Value: "gain from using kubecfg. objects through ownersReferences on them."},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "license"},
		{Type: PortfileTokenIdent, Value: "Apache-2.0", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "checksums"},
		{Type: PortfileTokenIdent, StartPos: 20, Value: "rmd160  f0dfa68de7f98847399f064aa8930d39483db97e \\"},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, StartPos: 20, Value: "sha256  322ed2b6d4214bafac63ee3d666aa240b077a0949d68bc97e5b6dfc484345b7e \\"},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, StartPos: 20, Value: "size    266525"},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "categories"},
		{Type: PortfileTokenIdent, Value: "sysutils", StartPos: 16},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "platforms"},
		{Type: PortfileTokenIdent, Value: "darwin", StartPos: 16},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "supported_archs"},
		{Type: PortfileTokenIdent, Value: "x86_64 arm64", StartPos: 16},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "installs_libs"},
		{Type: PortfileTokenIdent, Value: "no", StartPos: 16},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "build.cmd"},
		{Type: PortfileTokenIdent, Value: "make", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "build.target"},
		{Type: PortfileTokenIdent, Value: "kubecfg", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "build.post_args"},
		{Type: PortfileTokenIdent, Value: "VERSION=v${version}", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "build.env-delete"},
		{Type: PortfileTokenIdent, Value: "GO111MODULE=off GOPROXY=off", StartPos: 17},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "destroot"},
		{Type: PortfileTokenLBracket, StartPos: 9},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenIdent, Value: "xinstall -m 0755 ${worksrcpath}/${name} ${destroot}${prefix}/bin/", StartPos: 4},
		{Type: PortfileTokenLineBreak},
		{Type: PortfileTokenRBracket, StartPos: 0},
	}

	got, err := Output(tokens)
	require.NoError(t, err)
	assert.Contains(t, got, "PortSystem 1.0")
	assert.Contains(t, got, "checksums           rmd160  f0dfa68de7f98847399f064aa8930d39483db97e ")
}
