// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/text/converter/common.proto

package converter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_HTML Format = 0
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "HTML",
	}
	Format_value = map[string]int32{
		"HTML": 0,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_text_converter_common_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_proto_text_converter_common_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_proto_text_converter_common_proto_rawDescGZIP(), []int{0}
}

type RequestConvert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            string                 `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	Format        Format                 `protobuf:"varint,2,opt,name=format,proto3,enum=mono.text.converter.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestConvert) Reset() {
	*x = RequestConvert{}
	mi := &file_proto_text_converter_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestConvert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConvert) ProtoMessage() {}

func (x *RequestConvert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_converter_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConvert.ProtoReflect.Descriptor instead.
func (*RequestConvert) Descriptor() ([]byte, []int) {
	return file_proto_text_converter_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestConvert) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *RequestConvert) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_HTML
}

type ResponseConvert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Out           string                 `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseConvert) Reset() {
	*x = ResponseConvert{}
	mi := &file_proto_text_converter_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseConvert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseConvert) ProtoMessage() {}

func (x *ResponseConvert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_converter_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseConvert.ProtoReflect.Descriptor instead.
func (*ResponseConvert) Descriptor() ([]byte, []int) {
	return file_proto_text_converter_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseConvert) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

var File_proto_text_converter_common_proto protoreflect.FileDescriptor

const file_proto_text_converter_common_proto_rawDesc = "" +
	"\n" +
	"!proto/text/converter/common.proto\x12\x13mono.text.converter\"U\n" +
	"\x0eRequestConvert\x12\x0e\n" +
	"\x02in\x18\x01 \x01(\tR\x02in\x123\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1b.mono.text.converter.FormatR\x06format\"#\n" +
	"\x0fResponseConvert\x12\x10\n" +
	"\x03out\x18\x01 \x01(\tR\x03out*\x12\n" +
	"\x06Format\x12\b\n" +
	"\x04HTML\x10\x00B$Z\"go.f110.dev/mono/go/text/converterb\x06proto3"

var (
	file_proto_text_converter_common_proto_rawDescOnce sync.Once
	file_proto_text_converter_common_proto_rawDescData []byte
)

func file_proto_text_converter_common_proto_rawDescGZIP() []byte {
	file_proto_text_converter_common_proto_rawDescOnce.Do(func() {
		file_proto_text_converter_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_text_converter_common_proto_rawDesc), len(file_proto_text_converter_common_proto_rawDesc)))
	})
	return file_proto_text_converter_common_proto_rawDescData
}

var file_proto_text_converter_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_text_converter_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_text_converter_common_proto_goTypes = []any{
	(Format)(0),             // 0: mono.text.converter.Format
	(*RequestConvert)(nil),  // 1: mono.text.converter.RequestConvert
	(*ResponseConvert)(nil), // 2: mono.text.converter.ResponseConvert
}
var file_proto_text_converter_common_proto_depIdxs = []int32{
	0, // 0: mono.text.converter.RequestConvert.format:type_name -> mono.text.converter.Format
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_text_converter_common_proto_init() }
func file_proto_text_converter_common_proto_init() {
	if File_proto_text_converter_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_text_converter_common_proto_rawDesc), len(file_proto_text_converter_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_text_converter_common_proto_goTypes,
		DependencyIndexes: file_proto_text_converter_common_proto_depIdxs,
		EnumInfos:         file_proto_text_converter_common_proto_enumTypes,
		MessageInfos:      file_proto_text_converter_common_proto_msgTypes,
	}.Build()
	File_proto_text_converter_common_proto = out.File
	file_proto_text_converter_common_proto_goTypes = nil
	file_proto_text_converter_common_proto_depIdxs = nil
}
