// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/text/converter/rst.proto

package converter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_text_converter_rst_proto protoreflect.FileDescriptor

const file_proto_text_converter_rst_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/text/converter/rst.proto\x12\x13mono.text.converter\x1a!proto/text/converter/common.proto2q\n" +
	"\x19ReStructuredTextConverter\x12T\n" +
	"\aConvert\x12#.mono.text.converter.RequestConvert\x1a$.mono.text.converter.ResponseConvertB$Z\"go.f110.dev/mono/go/text/converterb\x06proto3"

var file_proto_text_converter_rst_proto_goTypes = []any{
	(*RequestConvert)(nil),  // 0: mono.text.converter.RequestConvert
	(*ResponseConvert)(nil), // 1: mono.text.converter.ResponseConvert
}
var file_proto_text_converter_rst_proto_depIdxs = []int32{
	0, // 0: mono.text.converter.ReStructuredTextConverter.Convert:input_type -> mono.text.converter.RequestConvert
	1, // 1: mono.text.converter.ReStructuredTextConverter.Convert:output_type -> mono.text.converter.ResponseConvert
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_text_converter_rst_proto_init() }
func file_proto_text_converter_rst_proto_init() {
	if File_proto_text_converter_rst_proto != nil {
		return
	}
	file_proto_text_converter_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_text_converter_rst_proto_rawDesc), len(file_proto_text_converter_rst_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_text_converter_rst_proto_goTypes,
		DependencyIndexes: file_proto_text_converter_rst_proto_depIdxs,
	}.Build()
	File_proto_text_converter_rst_proto = out.File
	file_proto_text_converter_rst_proto_goTypes = nil
	file_proto_text_converter_rst_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReStructuredTextConverterClient is the client API for ReStructuredTextConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReStructuredTextConverterClient interface {
	Convert(ctx context.Context, in *RequestConvert, opts ...grpc.CallOption) (*ResponseConvert, error)
}

type reStructuredTextConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewReStructuredTextConverterClient(cc grpc.ClientConnInterface) ReStructuredTextConverterClient {
	return &reStructuredTextConverterClient{cc}
}

func (c *reStructuredTextConverterClient) Convert(ctx context.Context, in *RequestConvert, opts ...grpc.CallOption) (*ResponseConvert, error) {
	out := new(ResponseConvert)
	err := c.cc.Invoke(ctx, "/mono.text.converter.ReStructuredTextConverter/Convert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReStructuredTextConverterServer is the server API for ReStructuredTextConverter service.
type ReStructuredTextConverterServer interface {
	Convert(context.Context, *RequestConvert) (*ResponseConvert, error)
}

// UnimplementedReStructuredTextConverterServer can be embedded to have forward compatible implementations.
type UnimplementedReStructuredTextConverterServer struct {
}

func (*UnimplementedReStructuredTextConverterServer) Convert(context.Context, *RequestConvert) (*ResponseConvert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}

func RegisterReStructuredTextConverterServer(s *grpc.Server, srv ReStructuredTextConverterServer) {
	s.RegisterService(&_ReStructuredTextConverter_serviceDesc, srv)
}

func _ReStructuredTextConverter_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestConvert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReStructuredTextConverterServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.text.converter.ReStructuredTextConverter/Convert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReStructuredTextConverterServer).Convert(ctx, req.(*RequestConvert))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReStructuredTextConverter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mono.text.converter.ReStructuredTextConverter",
	HandlerType: (*ReStructuredTextConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _ReStructuredTextConverter_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/text/converter/rst.proto",
}
