// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: go/cmd/1p/onepassword.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Item) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RequestUnlock struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MasterPassword []byte                 `protobuf:"bytes,1,opt,name=master_password,json=masterPassword,proto3" json:"master_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestUnlock) Reset() {
	*x = RequestUnlock{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUnlock) ProtoMessage() {}

func (x *RequestUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUnlock.ProtoReflect.Descriptor instead.
func (*RequestUnlock) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{1}
}

func (x *RequestUnlock) GetMasterPassword() []byte {
	if x != nil {
		return x.MasterPassword
	}
	return nil
}

type ResponseUnlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUnlock) Reset() {
	*x = ResponseUnlock{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUnlock) ProtoMessage() {}

func (x *ResponseUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUnlock.ProtoReflect.Descriptor instead.
func (*ResponseUnlock) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseUnlock) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLock) Reset() {
	*x = RequestLock{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLock) ProtoMessage() {}

func (x *RequestLock) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLock.ProtoReflect.Descriptor instead.
func (*RequestLock) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{3}
}

type ResponseLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseLock) Reset() {
	*x = ResponseLock{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseLock) ProtoMessage() {}

func (x *ResponseLock) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseLock.ProtoReflect.Descriptor instead.
func (*ResponseLock) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{4}
}

type RequestUseVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUseVault) Reset() {
	*x = RequestUseVault{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUseVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUseVault) ProtoMessage() {}

func (x *RequestUseVault) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUseVault.ProtoReflect.Descriptor instead.
func (*RequestUseVault) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{5}
}

func (x *RequestUseVault) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ResponseUseVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUseVault) Reset() {
	*x = ResponseUseVault{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUseVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUseVault) ProtoMessage() {}

func (x *ResponseUseVault) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUseVault.ProtoReflect.Descriptor instead.
func (*ResponseUseVault) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{6}
}

type RequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{7}
}

type ResponseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Locked        bool                   `protobuf:"varint,2,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseInfo) Reset() {
	*x = ResponseInfo{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInfo) ProtoMessage() {}

func (x *ResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInfo.ProtoReflect.Descriptor instead.
func (*ResponseInfo) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ResponseInfo) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

type RequestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestList) Reset() {
	*x = RequestList{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestList) ProtoMessage() {}

func (x *RequestList) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestList.ProtoReflect.Descriptor instead.
func (*RequestList) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{9}
}

type ResponseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseList) Reset() {
	*x = ResponseList{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseList) ProtoMessage() {}

func (x *ResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseList.ProtoReflect.Descriptor instead.
func (*ResponseList) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseList) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type RequestGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGet) Reset() {
	*x = RequestGet{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGet) ProtoMessage() {}

func (x *RequestGet) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGet.ProtoReflect.Descriptor instead.
func (*RequestGet) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{11}
}

func (x *RequestGet) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ResponseGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGet) Reset() {
	*x = ResponseGet{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGet) ProtoMessage() {}

func (x *ResponseGet) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGet.ProtoReflect.Descriptor instead.
func (*ResponseGet) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseGet) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type RequestSetClipboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSetClipboard) Reset() {
	*x = RequestSetClipboard{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSetClipboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSetClipboard) ProtoMessage() {}

func (x *RequestSetClipboard) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSetClipboard.ProtoReflect.Descriptor instead.
func (*RequestSetClipboard) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{13}
}

func (x *RequestSetClipboard) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ResponseSetClipboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseSetClipboard) Reset() {
	*x = ResponseSetClipboard{}
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseSetClipboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSetClipboard) ProtoMessage() {}

func (x *ResponseSetClipboard) ProtoReflect() protoreflect.Message {
	mi := &file_go_cmd_1p_onepassword_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSetClipboard.ProtoReflect.Descriptor instead.
func (*ResponseSetClipboard) Descriptor() ([]byte, []int) {
	return file_go_cmd_1p_onepassword_proto_rawDescGZIP(), []int{14}
}

var File_go_cmd_1p_onepassword_proto protoreflect.FileDescriptor

const file_go_cmd_1p_onepassword_proto_rawDesc = "" +
	"\n" +
	"\x1bgo/cmd/1p/onepassword.proto\x12\x10mono.onepassword\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\x04Item\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"8\n" +
	"\rRequestUnlock\x12'\n" +
	"\x0fmaster_password\x18\x01 \x01(\fR\x0emasterPassword\"*\n" +
	"\x0eResponseUnlock\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vRequestLock\"\x0e\n" +
	"\fResponseLock\"%\n" +
	"\x0fRequestUseVault\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x12\n" +
	"\x10ResponseUseVault\"\r\n" +
	"\vRequestInfo\":\n" +
	"\fResponseInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06locked\x18\x02 \x01(\bR\x06locked\"\r\n" +
	"\vRequestList\"<\n" +
	"\fResponseList\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.mono.onepassword.ItemR\x05items\" \n" +
	"\n" +
	"RequestGet\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"9\n" +
	"\vResponseGet\x12*\n" +
	"\x04item\x18\x01 \x01(\v2\x16.mono.onepassword.ItemR\x04item\")\n" +
	"\x13RequestSetClipboard\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x16\n" +
	"\x14ResponseSetClipboard2\xa5\x04\n" +
	"\vOnePassword\x12K\n" +
	"\x06Unlock\x12\x1f.mono.onepassword.RequestUnlock\x1a .mono.onepassword.ResponseUnlock\x12E\n" +
	"\x04Lock\x12\x1d.mono.onepassword.RequestLock\x1a\x1e.mono.onepassword.ResponseLock\x12Q\n" +
	"\bUseVault\x12!.mono.onepassword.RequestUseVault\x1a\".mono.onepassword.ResponseUseVault\x12E\n" +
	"\x04Info\x12\x1d.mono.onepassword.RequestInfo\x1a\x1e.mono.onepassword.ResponseInfo\x12E\n" +
	"\x04List\x12\x1d.mono.onepassword.RequestList\x1a\x1e.mono.onepassword.ResponseList\x12B\n" +
	"\x03Get\x12\x1c.mono.onepassword.RequestGet\x1a\x1d.mono.onepassword.ResponseGet\x12]\n" +
	"\fSetClipboard\x12%.mono.onepassword.RequestSetClipboard\x1a&.mono.onepassword.ResponseSetClipboardB!Z\x1fgo.f110.dev/mono/go/cmd/1p;mainb\x06proto3"

var (
	file_go_cmd_1p_onepassword_proto_rawDescOnce sync.Once
	file_go_cmd_1p_onepassword_proto_rawDescData []byte
)

func file_go_cmd_1p_onepassword_proto_rawDescGZIP() []byte {
	file_go_cmd_1p_onepassword_proto_rawDescOnce.Do(func() {
		file_go_cmd_1p_onepassword_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_cmd_1p_onepassword_proto_rawDesc), len(file_go_cmd_1p_onepassword_proto_rawDesc)))
	})
	return file_go_cmd_1p_onepassword_proto_rawDescData
}

var file_go_cmd_1p_onepassword_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_go_cmd_1p_onepassword_proto_goTypes = []any{
	(*Item)(nil),                  // 0: mono.onepassword.Item
	(*RequestUnlock)(nil),         // 1: mono.onepassword.RequestUnlock
	(*ResponseUnlock)(nil),        // 2: mono.onepassword.ResponseUnlock
	(*RequestLock)(nil),           // 3: mono.onepassword.RequestLock
	(*ResponseLock)(nil),          // 4: mono.onepassword.ResponseLock
	(*RequestUseVault)(nil),       // 5: mono.onepassword.RequestUseVault
	(*ResponseUseVault)(nil),      // 6: mono.onepassword.ResponseUseVault
	(*RequestInfo)(nil),           // 7: mono.onepassword.RequestInfo
	(*ResponseInfo)(nil),          // 8: mono.onepassword.ResponseInfo
	(*RequestList)(nil),           // 9: mono.onepassword.RequestList
	(*ResponseList)(nil),          // 10: mono.onepassword.ResponseList
	(*RequestGet)(nil),            // 11: mono.onepassword.RequestGet
	(*ResponseGet)(nil),           // 12: mono.onepassword.ResponseGet
	(*RequestSetClipboard)(nil),   // 13: mono.onepassword.RequestSetClipboard
	(*ResponseSetClipboard)(nil),  // 14: mono.onepassword.ResponseSetClipboard
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_go_cmd_1p_onepassword_proto_depIdxs = []int32{
	15, // 0: mono.onepassword.Item.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: mono.onepassword.Item.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: mono.onepassword.ResponseList.items:type_name -> mono.onepassword.Item
	0,  // 3: mono.onepassword.ResponseGet.item:type_name -> mono.onepassword.Item
	1,  // 4: mono.onepassword.OnePassword.Unlock:input_type -> mono.onepassword.RequestUnlock
	3,  // 5: mono.onepassword.OnePassword.Lock:input_type -> mono.onepassword.RequestLock
	5,  // 6: mono.onepassword.OnePassword.UseVault:input_type -> mono.onepassword.RequestUseVault
	7,  // 7: mono.onepassword.OnePassword.Info:input_type -> mono.onepassword.RequestInfo
	9,  // 8: mono.onepassword.OnePassword.List:input_type -> mono.onepassword.RequestList
	11, // 9: mono.onepassword.OnePassword.Get:input_type -> mono.onepassword.RequestGet
	13, // 10: mono.onepassword.OnePassword.SetClipboard:input_type -> mono.onepassword.RequestSetClipboard
	2,  // 11: mono.onepassword.OnePassword.Unlock:output_type -> mono.onepassword.ResponseUnlock
	4,  // 12: mono.onepassword.OnePassword.Lock:output_type -> mono.onepassword.ResponseLock
	6,  // 13: mono.onepassword.OnePassword.UseVault:output_type -> mono.onepassword.ResponseUseVault
	8,  // 14: mono.onepassword.OnePassword.Info:output_type -> mono.onepassword.ResponseInfo
	10, // 15: mono.onepassword.OnePassword.List:output_type -> mono.onepassword.ResponseList
	12, // 16: mono.onepassword.OnePassword.Get:output_type -> mono.onepassword.ResponseGet
	14, // 17: mono.onepassword.OnePassword.SetClipboard:output_type -> mono.onepassword.ResponseSetClipboard
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_go_cmd_1p_onepassword_proto_init() }
func file_go_cmd_1p_onepassword_proto_init() {
	if File_go_cmd_1p_onepassword_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_cmd_1p_onepassword_proto_rawDesc), len(file_go_cmd_1p_onepassword_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_cmd_1p_onepassword_proto_goTypes,
		DependencyIndexes: file_go_cmd_1p_onepassword_proto_depIdxs,
		MessageInfos:      file_go_cmd_1p_onepassword_proto_msgTypes,
	}.Build()
	File_go_cmd_1p_onepassword_proto = out.File
	file_go_cmd_1p_onepassword_proto_goTypes = nil
	file_go_cmd_1p_onepassword_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OnePasswordClient is the client API for OnePassword service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnePasswordClient interface {
	Unlock(ctx context.Context, in *RequestUnlock, opts ...grpc.CallOption) (*ResponseUnlock, error)
	Lock(ctx context.Context, in *RequestLock, opts ...grpc.CallOption) (*ResponseLock, error)
	UseVault(ctx context.Context, in *RequestUseVault, opts ...grpc.CallOption) (*ResponseUseVault, error)
	Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error)
	List(ctx context.Context, in *RequestList, opts ...grpc.CallOption) (*ResponseList, error)
	Get(ctx context.Context, in *RequestGet, opts ...grpc.CallOption) (*ResponseGet, error)
	SetClipboard(ctx context.Context, in *RequestSetClipboard, opts ...grpc.CallOption) (*ResponseSetClipboard, error)
}

type onePasswordClient struct {
	cc grpc.ClientConnInterface
}

func NewOnePasswordClient(cc grpc.ClientConnInterface) OnePasswordClient {
	return &onePasswordClient{cc}
}

func (c *onePasswordClient) Unlock(ctx context.Context, in *RequestUnlock, opts ...grpc.CallOption) (*ResponseUnlock, error) {
	out := new(ResponseUnlock)
	err := c.cc.Invoke(ctx, "/mono.onepassword.OnePassword/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onePasswordClient) Lock(ctx context.Context, in *RequestLock, opts ...grpc.CallOption) (*ResponseLock, error) {
	out := new(ResponseLock)
	err := c.cc.Invoke(ctx, "/mono.onepassword.OnePassword/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onePasswordClient) UseVault(ctx context.Context, in *RequestUseVault, opts ...grpc.CallOption) (*ResponseUseVault, error) {
	out := new(ResponseUseVault)
	err := c.cc.Invoke(ctx, "/mono.onepassword.OnePassword/UseVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onePasswordClient) Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error) {
	out := new(ResponseInfo)
	err := c.cc.Invoke(ctx, "/mono.onepassword.OnePassword/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onePasswordClient) List(ctx context.Context, in *RequestList, opts ...grpc.CallOption) (*ResponseList, error) {
	out := new(ResponseList)
	err := c.cc.Invoke(ctx, "/mono.onepassword.OnePassword/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onePasswordClient) Get(ctx context.Context, in *RequestGet, opts ...grpc.CallOption) (*ResponseGet, error) {
	out := new(ResponseGet)
	err := c.cc.Invoke(ctx, "/mono.onepassword.OnePassword/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onePasswordClient) SetClipboard(ctx context.Context, in *RequestSetClipboard, opts ...grpc.CallOption) (*ResponseSetClipboard, error) {
	out := new(ResponseSetClipboard)
	err := c.cc.Invoke(ctx, "/mono.onepassword.OnePassword/SetClipboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnePasswordServer is the server API for OnePassword service.
type OnePasswordServer interface {
	Unlock(context.Context, *RequestUnlock) (*ResponseUnlock, error)
	Lock(context.Context, *RequestLock) (*ResponseLock, error)
	UseVault(context.Context, *RequestUseVault) (*ResponseUseVault, error)
	Info(context.Context, *RequestInfo) (*ResponseInfo, error)
	List(context.Context, *RequestList) (*ResponseList, error)
	Get(context.Context, *RequestGet) (*ResponseGet, error)
	SetClipboard(context.Context, *RequestSetClipboard) (*ResponseSetClipboard, error)
}

// UnimplementedOnePasswordServer can be embedded to have forward compatible implementations.
type UnimplementedOnePasswordServer struct {
}

func (*UnimplementedOnePasswordServer) Unlock(context.Context, *RequestUnlock) (*ResponseUnlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedOnePasswordServer) Lock(context.Context, *RequestLock) (*ResponseLock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedOnePasswordServer) UseVault(context.Context, *RequestUseVault) (*ResponseUseVault, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseVault not implemented")
}
func (*UnimplementedOnePasswordServer) Info(context.Context, *RequestInfo) (*ResponseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedOnePasswordServer) List(context.Context, *RequestList) (*ResponseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedOnePasswordServer) Get(context.Context, *RequestGet) (*ResponseGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedOnePasswordServer) SetClipboard(context.Context, *RequestSetClipboard) (*ResponseSetClipboard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetClipboard not implemented")
}

func RegisterOnePasswordServer(s *grpc.Server, srv OnePasswordServer) {
	s.RegisterService(&_OnePassword_serviceDesc, srv)
}

func _OnePassword_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUnlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnePasswordServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.onepassword.OnePassword/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnePasswordServer).Unlock(ctx, req.(*RequestUnlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnePassword_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnePasswordServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.onepassword.OnePassword/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnePasswordServer).Lock(ctx, req.(*RequestLock))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnePassword_UseVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUseVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnePasswordServer).UseVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.onepassword.OnePassword/UseVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnePasswordServer).UseVault(ctx, req.(*RequestUseVault))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnePassword_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnePasswordServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.onepassword.OnePassword/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnePasswordServer).Info(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnePassword_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnePasswordServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.onepassword.OnePassword/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnePasswordServer).List(ctx, req.(*RequestList))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnePassword_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnePasswordServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.onepassword.OnePassword/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnePasswordServer).Get(ctx, req.(*RequestGet))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnePassword_SetClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSetClipboard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnePasswordServer).SetClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.onepassword.OnePassword/SetClipboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnePasswordServer).SetClipboard(ctx, req.(*RequestSetClipboard))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnePassword_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mono.onepassword.OnePassword",
	HandlerType: (*OnePasswordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unlock",
			Handler:    _OnePassword_Unlock_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _OnePassword_Lock_Handler,
		},
		{
			MethodName: "UseVault",
			Handler:    _OnePassword_UseVault_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _OnePassword_Info_Handler,
		},
		{
			MethodName: "List",
			Handler:    _OnePassword_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OnePassword_Get_Handler,
		},
		{
			MethodName: "SetClipboard",
			Handler:    _OnePassword_SetClipboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go/cmd/1p/onepassword.proto",
}
