
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: consul-admin
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - pods/portforward
  verbs:
  - create
  - get
  - list
- apiGroups:
  - consul.f110.dev
  resources:
  - consulbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consul.f110.dev
  resources:
  - consulbackups/status
  verbs:
  - get
  - patch
  - update
