apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-extra-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-extra-operator
subjects:
  - kind: ServiceAccount
    name: minio-extra-operator
    namespace: default
