/*
MIT License

Copyright (c) 2020 Fumihiro Ito

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "go.f110.dev/mono/go/pkg/api/minio/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MinIOBucketLister helps list MinIOBuckets.
// All objects returned here must be treated as read-only.
type MinIOBucketLister interface {
	// List lists all MinIOBuckets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MinIOBucket, err error)
	// MinIOBuckets returns an object that can list and get MinIOBuckets.
	MinIOBuckets(namespace string) MinIOBucketNamespaceLister
	MinIOBucketListerExpansion
}

// minIOBucketLister implements the MinIOBucketLister interface.
type minIOBucketLister struct {
	indexer cache.Indexer
}

// NewMinIOBucketLister returns a new MinIOBucketLister.
func NewMinIOBucketLister(indexer cache.Indexer) MinIOBucketLister {
	return &minIOBucketLister{indexer: indexer}
}

// List lists all MinIOBuckets in the indexer.
func (s *minIOBucketLister) List(selector labels.Selector) (ret []*v1alpha1.MinIOBucket, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MinIOBucket))
	})
	return ret, err
}

// MinIOBuckets returns an object that can list and get MinIOBuckets.
func (s *minIOBucketLister) MinIOBuckets(namespace string) MinIOBucketNamespaceLister {
	return minIOBucketNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MinIOBucketNamespaceLister helps list and get MinIOBuckets.
// All objects returned here must be treated as read-only.
type MinIOBucketNamespaceLister interface {
	// List lists all MinIOBuckets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MinIOBucket, err error)
	// Get retrieves the MinIOBucket from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.MinIOBucket, error)
	MinIOBucketNamespaceListerExpansion
}

// minIOBucketNamespaceLister implements the MinIOBucketNamespaceLister
// interface.
type minIOBucketNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MinIOBuckets in the indexer for a given namespace.
func (s minIOBucketNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MinIOBucket, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MinIOBucket))
	})
	return ret, err
}

// Get retrieves the MinIOBucket from the indexer for a given namespace and name.
func (s minIOBucketNamespaceLister) Get(name string) (*v1alpha1.MinIOBucket, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("miniobucket"), name)
	}
	return obj.(*v1alpha1.MinIOBucket), nil
}
