// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0--rc2
// source: proto/text/converter/common.proto

package converter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_HTML Format = 0
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "HTML",
	}
	Format_value = map[string]int32{
		"HTML": 0,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_text_converter_common_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_proto_text_converter_common_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_proto_text_converter_common_proto_rawDescGZIP(), []int{0}
}

type RequestConvert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In     string `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	Format Format `protobuf:"varint,2,opt,name=format,proto3,enum=mono.text.converter.Format" json:"format,omitempty"`
}

func (x *RequestConvert) Reset() {
	*x = RequestConvert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_text_converter_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestConvert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestConvert) ProtoMessage() {}

func (x *RequestConvert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_converter_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestConvert.ProtoReflect.Descriptor instead.
func (*RequestConvert) Descriptor() ([]byte, []int) {
	return file_proto_text_converter_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestConvert) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *RequestConvert) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_HTML
}

type ResponseConvert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Out string `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *ResponseConvert) Reset() {
	*x = ResponseConvert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_text_converter_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseConvert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseConvert) ProtoMessage() {}

func (x *ResponseConvert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_converter_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseConvert.ProtoReflect.Descriptor instead.
func (*ResponseConvert) Descriptor() ([]byte, []int) {
	return file_proto_text_converter_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseConvert) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

var File_proto_text_converter_common_proto protoreflect.FileDescriptor

var file_proto_text_converter_common_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x2f, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6d, 0x6f, 0x6e, 0x6f, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x22, 0x55, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x33, 0x0a, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x6e,
	0x6f, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22,
	0x23, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6f, 0x75, 0x74, 0x2a, 0x12, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x08,
	0x0a, 0x04, 0x48, 0x54, 0x4d, 0x4c, 0x10, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x6f, 0x2e, 0x66,
	0x31, 0x31, 0x30, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x67, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_text_converter_common_proto_rawDescOnce sync.Once
	file_proto_text_converter_common_proto_rawDescData = file_proto_text_converter_common_proto_rawDesc
)

func file_proto_text_converter_common_proto_rawDescGZIP() []byte {
	file_proto_text_converter_common_proto_rawDescOnce.Do(func() {
		file_proto_text_converter_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_text_converter_common_proto_rawDescData)
	})
	return file_proto_text_converter_common_proto_rawDescData
}

var file_proto_text_converter_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_text_converter_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_text_converter_common_proto_goTypes = []interface{}{
	(Format)(0),             // 0: mono.text.converter.Format
	(*RequestConvert)(nil),  // 1: mono.text.converter.RequestConvert
	(*ResponseConvert)(nil), // 2: mono.text.converter.ResponseConvert
}
var file_proto_text_converter_common_proto_depIdxs = []int32{
	0, // 0: mono.text.converter.RequestConvert.format:type_name -> mono.text.converter.Format
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_text_converter_common_proto_init() }
func file_proto_text_converter_common_proto_init() {
	if File_proto_text_converter_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_text_converter_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestConvert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_text_converter_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseConvert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_text_converter_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_text_converter_common_proto_goTypes,
		DependencyIndexes: file_proto_text_converter_common_proto_depIdxs,
		EnumInfos:         file_proto_text_converter_common_proto_enumTypes,
		MessageInfos:      file_proto_text_converter_common_proto_msgTypes,
	}.Build()
	File_proto_text_converter_common_proto = out.File
	file_proto_text_converter_common_proto_rawDesc = nil
	file_proto_text_converter_common_proto_goTypes = nil
	file_proto_text_converter_common_proto_depIdxs = nil
}
