/*
MIT License

Copyright (c) 2020 Fumihiro Ito

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/minio/minio-operator/pkg/apis/miniocontroller/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MirrorLister helps list Mirrors.
// All objects returned here must be treated as read-only.
type MirrorLister interface {
	// List lists all Mirrors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.Mirror, err error)
	// Mirrors returns an object that can list and get Mirrors.
	Mirrors(namespace string) MirrorNamespaceLister
	MirrorListerExpansion
}

// mirrorLister implements the MirrorLister interface.
type mirrorLister struct {
	indexer cache.Indexer
}

// NewMirrorLister returns a new MirrorLister.
func NewMirrorLister(indexer cache.Indexer) MirrorLister {
	return &mirrorLister{indexer: indexer}
}

// List lists all Mirrors in the indexer.
func (s *mirrorLister) List(selector labels.Selector) (ret []*v1beta1.Mirror, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Mirror))
	})
	return ret, err
}

// Mirrors returns an object that can list and get Mirrors.
func (s *mirrorLister) Mirrors(namespace string) MirrorNamespaceLister {
	return mirrorNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MirrorNamespaceLister helps list and get Mirrors.
// All objects returned here must be treated as read-only.
type MirrorNamespaceLister interface {
	// List lists all Mirrors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.Mirror, err error)
	// Get retrieves the Mirror from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.Mirror, error)
	MirrorNamespaceListerExpansion
}

// mirrorNamespaceLister implements the MirrorNamespaceLister
// interface.
type mirrorNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Mirrors in the indexer for a given namespace.
func (s mirrorNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.Mirror, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Mirror))
	})
	return ret, err
}

// Get retrieves the Mirror from the indexer for a given namespace and name.
func (s mirrorNamespaceLister) Get(name string) (*v1beta1.Mirror, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("mirror"), name)
	}
	return obj.(*v1beta1.Mirror), nil
}
