// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/docutil/search.proto

package docutil

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkType int32

const (
	LinkType_LINK_TYPE_EXTERNAL            LinkType = 0
	LinkType_LINK_TYPE_IN_REPOSITORY       LinkType = 1
	LinkType_LINK_TYPE_NEIGHBOR_REPOSITORY LinkType = 2
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0: "LINK_TYPE_EXTERNAL",
		1: "LINK_TYPE_IN_REPOSITORY",
		2: "LINK_TYPE_NEIGHBOR_REPOSITORY",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_EXTERNAL":            0,
		"LINK_TYPE_IN_REPOSITORY":       1,
		"LINK_TYPE_NEIGHBOR_REPOSITORY": 2,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_docutil_search_proto_enumTypes[0].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_proto_docutil_search_proto_enumTypes[0]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{0}
}

type RequestAvailableFeatures struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestAvailableFeatures) Reset() {
	*x = RequestAvailableFeatures{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_docutil_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAvailableFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAvailableFeatures) ProtoMessage() {}

func (x *RequestAvailableFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAvailableFeatures.ProtoReflect.Descriptor instead.
func (*RequestAvailableFeatures) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{0}
}

type ResponseAvailableFeatures struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageLink       bool `protobuf:"varint,1,opt,name=page_link,json=pageLink,proto3" json:"page_link,omitempty"`
	FullTextSearch bool `protobuf:"varint,2,opt,name=full_text_search,json=fullTextSearch,proto3" json:"full_text_search,omitempty"`
}

func (x *ResponseAvailableFeatures) Reset() {
	*x = ResponseAvailableFeatures{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_docutil_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAvailableFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAvailableFeatures) ProtoMessage() {}

func (x *ResponseAvailableFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAvailableFeatures.ProtoReflect.Descriptor instead.
func (*ResponseAvailableFeatures) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAvailableFeatures) GetPageLink() bool {
	if x != nil {
		return x.PageLink
	}
	return false
}

func (x *ResponseAvailableFeatures) GetFullTextSearch() bool {
	if x != nil {
		return x.FullTextSearch
	}
	return false
}

type RequestGetPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha string `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
}

func (x *RequestGetPage) Reset() {
	*x = RequestGetPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_docutil_search_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetPage) ProtoMessage() {}

func (x *RequestGetPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetPage.ProtoReflect.Descriptor instead.
func (*RequestGetPage) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGetPage) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type ResponseGetPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *ResponseGetPage) Reset() {
	*x = ResponseGetPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_docutil_search_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetPage) ProtoMessage() {}

func (x *ResponseGetPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetPage.ProtoReflect.Descriptor instead.
func (*ResponseGetPage) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseGetPage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type PageLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        LinkType `protobuf:"varint,1,opt,name=type,proto3,enum=mono.docutil.LinkType" json:"type,omitempty"`
	Source      string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Repository  string   `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Title       string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *PageLink) Reset() {
	*x = PageLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_docutil_search_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageLink) ProtoMessage() {}

func (x *PageLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageLink.ProtoReflect.Descriptor instead.
func (*PageLink) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{4}
}

func (x *PageLink) GetType() LinkType {
	if x != nil {
		return x.Type
	}
	return LinkType_LINK_TYPE_EXTERNAL
}

func (x *PageLink) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PageLink) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PageLink) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *PageLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RequestPageLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Sha  string `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
}

func (x *RequestPageLink) Reset() {
	*x = RequestPageLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_docutil_search_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPageLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPageLink) ProtoMessage() {}

func (x *RequestPageLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPageLink.ProtoReflect.Descriptor instead.
func (*RequestPageLink) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{5}
}

func (x *RequestPageLink) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RequestPageLink) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type ResponsePageLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In  []*PageLink `protobuf:"bytes,1,rep,name=in,proto3" json:"in,omitempty"`
	Out []*PageLink `protobuf:"bytes,2,rep,name=out,proto3" json:"out,omitempty"`
}

func (x *ResponsePageLink) Reset() {
	*x = ResponsePageLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_docutil_search_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePageLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePageLink) ProtoMessage() {}

func (x *ResponsePageLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePageLink.ProtoReflect.Descriptor instead.
func (*ResponsePageLink) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{6}
}

func (x *ResponsePageLink) GetIn() []*PageLink {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *ResponsePageLink) GetOut() []*PageLink {
	if x != nil {
		return x.Out
	}
	return nil
}

var File_proto_docutil_search_proto protoreflect.FileDescriptor

var file_proto_docutil_search_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x2f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x6f,
	0x6e, 0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x62, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b,
	0x12, 0x28, 0x0a, 0x10, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x66, 0x75, 0x6c, 0x6c,
	0x54, 0x65, 0x78, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x22, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x68, 0x61, 0x22, 0x27,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x6e, 0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x37, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x68, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x68, 0x61, 0x22, 0x64, 0x0a, 0x10, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x26, 0x0a,
	0x02, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x6e, 0x6f,
	0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x6e, 0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x2a,
	0x62, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x4c,
	0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x4f, 0x52, 0x59, 0x10, 0x01,
	0x12, 0x21, 0x0a, 0x1d, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x45,
	0x49, 0x47, 0x48, 0x42, 0x4f, 0x52, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x4f, 0x52,
	0x59, 0x10, 0x02, 0x32, 0x84, 0x02, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x12, 0x64, 0x0a, 0x11, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x6d, 0x6f, 0x6e, 0x6f, 0x2e, 0x64, 0x6f,
	0x63, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x1a, 0x27,
	0x2e, 0x6d, 0x6f, 0x6e, 0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x6e, 0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x6e, 0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x49, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1d, 0x2e, 0x6d, 0x6f,
	0x6e, 0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x1e, 0x2e, 0x6d, 0x6f, 0x6e,
	0x6f, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x6f,
	0x2e, 0x66, 0x31, 0x31, 0x30, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x67,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x74, 0x69, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_docutil_search_proto_rawDescOnce sync.Once
	file_proto_docutil_search_proto_rawDescData = file_proto_docutil_search_proto_rawDesc
)

func file_proto_docutil_search_proto_rawDescGZIP() []byte {
	file_proto_docutil_search_proto_rawDescOnce.Do(func() {
		file_proto_docutil_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_docutil_search_proto_rawDescData)
	})
	return file_proto_docutil_search_proto_rawDescData
}

var file_proto_docutil_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_docutil_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_docutil_search_proto_goTypes = []interface{}{
	(LinkType)(0),                     // 0: mono.docutil.LinkType
	(*RequestAvailableFeatures)(nil),  // 1: mono.docutil.RequestAvailableFeatures
	(*ResponseAvailableFeatures)(nil), // 2: mono.docutil.ResponseAvailableFeatures
	(*RequestGetPage)(nil),            // 3: mono.docutil.RequestGetPage
	(*ResponseGetPage)(nil),           // 4: mono.docutil.ResponseGetPage
	(*PageLink)(nil),                  // 5: mono.docutil.PageLink
	(*RequestPageLink)(nil),           // 6: mono.docutil.RequestPageLink
	(*ResponsePageLink)(nil),          // 7: mono.docutil.ResponsePageLink
}
var file_proto_docutil_search_proto_depIdxs = []int32{
	0, // 0: mono.docutil.PageLink.type:type_name -> mono.docutil.LinkType
	5, // 1: mono.docutil.ResponsePageLink.in:type_name -> mono.docutil.PageLink
	5, // 2: mono.docutil.ResponsePageLink.out:type_name -> mono.docutil.PageLink
	1, // 3: mono.docutil.DocSearch.AvailableFeatures:input_type -> mono.docutil.RequestAvailableFeatures
	3, // 4: mono.docutil.DocSearch.GetPage:input_type -> mono.docutil.RequestGetPage
	6, // 5: mono.docutil.DocSearch.PageLink:input_type -> mono.docutil.RequestPageLink
	2, // 6: mono.docutil.DocSearch.AvailableFeatures:output_type -> mono.docutil.ResponseAvailableFeatures
	4, // 7: mono.docutil.DocSearch.GetPage:output_type -> mono.docutil.ResponseGetPage
	7, // 8: mono.docutil.DocSearch.PageLink:output_type -> mono.docutil.ResponsePageLink
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_docutil_search_proto_init() }
func file_proto_docutil_search_proto_init() {
	if File_proto_docutil_search_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_docutil_search_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAvailableFeatures); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_docutil_search_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAvailableFeatures); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_docutil_search_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_docutil_search_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_docutil_search_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_docutil_search_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPageLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_docutil_search_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePageLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_docutil_search_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_docutil_search_proto_goTypes,
		DependencyIndexes: file_proto_docutil_search_proto_depIdxs,
		EnumInfos:         file_proto_docutil_search_proto_enumTypes,
		MessageInfos:      file_proto_docutil_search_proto_msgTypes,
	}.Build()
	File_proto_docutil_search_proto = out.File
	file_proto_docutil_search_proto_rawDesc = nil
	file_proto_docutil_search_proto_goTypes = nil
	file_proto_docutil_search_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DocSearchClient is the client API for DocSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocSearchClient interface {
	AvailableFeatures(ctx context.Context, in *RequestAvailableFeatures, opts ...grpc.CallOption) (*ResponseAvailableFeatures, error)
	GetPage(ctx context.Context, in *RequestGetPage, opts ...grpc.CallOption) (*ResponseGetPage, error)
	PageLink(ctx context.Context, in *RequestPageLink, opts ...grpc.CallOption) (*ResponsePageLink, error)
}

type docSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewDocSearchClient(cc grpc.ClientConnInterface) DocSearchClient {
	return &docSearchClient{cc}
}

func (c *docSearchClient) AvailableFeatures(ctx context.Context, in *RequestAvailableFeatures, opts ...grpc.CallOption) (*ResponseAvailableFeatures, error) {
	out := new(ResponseAvailableFeatures)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/AvailableFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docSearchClient) GetPage(ctx context.Context, in *RequestGetPage, opts ...grpc.CallOption) (*ResponseGetPage, error) {
	out := new(ResponseGetPage)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docSearchClient) PageLink(ctx context.Context, in *RequestPageLink, opts ...grpc.CallOption) (*ResponsePageLink, error) {
	out := new(ResponsePageLink)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/PageLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocSearchServer is the server API for DocSearch service.
type DocSearchServer interface {
	AvailableFeatures(context.Context, *RequestAvailableFeatures) (*ResponseAvailableFeatures, error)
	GetPage(context.Context, *RequestGetPage) (*ResponseGetPage, error)
	PageLink(context.Context, *RequestPageLink) (*ResponsePageLink, error)
}

// UnimplementedDocSearchServer can be embedded to have forward compatible implementations.
type UnimplementedDocSearchServer struct {
}

func (*UnimplementedDocSearchServer) AvailableFeatures(context.Context, *RequestAvailableFeatures) (*ResponseAvailableFeatures, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvailableFeatures not implemented")
}
func (*UnimplementedDocSearchServer) GetPage(context.Context, *RequestGetPage) (*ResponseGetPage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (*UnimplementedDocSearchServer) PageLink(context.Context, *RequestPageLink) (*ResponsePageLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageLink not implemented")
}

func RegisterDocSearchServer(s *grpc.Server, srv DocSearchServer) {
	s.RegisterService(&_DocSearch_serviceDesc, srv)
}

func _DocSearch_AvailableFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAvailableFeatures)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).AvailableFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/AvailableFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).AvailableFeatures(ctx, req.(*RequestAvailableFeatures))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocSearch_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetPage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).GetPage(ctx, req.(*RequestGetPage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocSearch_PageLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPageLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).PageLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/PageLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).PageLink(ctx, req.(*RequestPageLink))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocSearch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mono.docutil.DocSearch",
	HandlerType: (*DocSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvailableFeatures",
			Handler:    _DocSearch_AvailableFeatures_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _DocSearch_GetPage_Handler,
		},
		{
			MethodName: "PageLink",
			Handler:    _DocSearch_PageLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/docutil/search.proto",
}
