apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minioinstances.miniocontroller.min.io
spec:
  group: miniocontroller.min.io
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 32
                version:
                  type: string
                mountpath:
                  type: string
                subpath:
                  type: string
  names:
    kind: MinIOInstance
    singular: minioinstance
    plural: minioinstances
