// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/docutil/search.proto

package docutil

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FILE_TYPE_MARKDOWN FileType = 0
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_MARKDOWN",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_MARKDOWN": 0,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_docutil_search_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_proto_docutil_search_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{0}
}

type LinkType int32

const (
	LinkType_LINK_TYPE_EXTERNAL            LinkType = 0
	LinkType_LINK_TYPE_IN_REPOSITORY       LinkType = 1
	LinkType_LINK_TYPE_NEIGHBOR_REPOSITORY LinkType = 2
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0: "LINK_TYPE_EXTERNAL",
		1: "LINK_TYPE_IN_REPOSITORY",
		2: "LINK_TYPE_NEIGHBOR_REPOSITORY",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_EXTERNAL":            0,
		"LINK_TYPE_IN_REPOSITORY":       1,
		"LINK_TYPE_NEIGHBOR_REPOSITORY": 2,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_docutil_search_proto_enumTypes[1].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_proto_docutil_search_proto_enumTypes[1]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{1}
}

type RequestAvailableFeatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAvailableFeatures) Reset() {
	*x = RequestAvailableFeatures{}
	mi := &file_proto_docutil_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAvailableFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAvailableFeatures) ProtoMessage() {}

func (x *RequestAvailableFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAvailableFeatures.ProtoReflect.Descriptor instead.
func (*RequestAvailableFeatures) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{0}
}

type ResponseAvailableFeatures struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PageLink          bool                   `protobuf:"varint,1,opt,name=page_link,json=pageLink,proto3" json:"page_link,omitempty"`
	FullTextSearch    bool                   `protobuf:"varint,2,opt,name=full_text_search,json=fullTextSearch,proto3" json:"full_text_search,omitempty"`
	SupportedFileType []FileType             `protobuf:"varint,3,rep,packed,name=supported_file_type,json=supportedFileType,proto3,enum=mono.docutil.FileType" json:"supported_file_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResponseAvailableFeatures) Reset() {
	*x = ResponseAvailableFeatures{}
	mi := &file_proto_docutil_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAvailableFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAvailableFeatures) ProtoMessage() {}

func (x *ResponseAvailableFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAvailableFeatures.ProtoReflect.Descriptor instead.
func (*ResponseAvailableFeatures) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAvailableFeatures) GetPageLink() bool {
	if x != nil {
		return x.PageLink
	}
	return false
}

func (x *ResponseAvailableFeatures) GetFullTextSearch() bool {
	if x != nil {
		return x.FullTextSearch
	}
	return false
}

func (x *ResponseAvailableFeatures) GetSupportedFileType() []FileType {
	if x != nil {
		return x.SupportedFileType
	}
	return nil
}

type RequestListRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestListRepository) Reset() {
	*x = RequestListRepository{}
	mi := &file_proto_docutil_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestListRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestListRepository) ProtoMessage() {}

func (x *RequestListRepository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestListRepository.ProtoReflect.Descriptor instead.
func (*RequestListRepository) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{2}
}

type ResponseListRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseListRepository) Reset() {
	*x = ResponseListRepository{}
	mi := &file_proto_docutil_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseListRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseListRepository) ProtoMessage() {}

func (x *ResponseListRepository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseListRepository.ProtoReflect.Descriptor instead.
func (*ResponseListRepository) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseListRepository) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type RequestGetRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetRepository) Reset() {
	*x = RequestGetRepository{}
	mi := &file_proto_docutil_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetRepository) ProtoMessage() {}

func (x *RequestGetRepository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetRepository.ProtoReflect.Descriptor instead.
func (*RequestGetRepository) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{4}
}

func (x *RequestGetRepository) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type ResponseGetRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetRepository) Reset() {
	*x = ResponseGetRepository{}
	mi := &file_proto_docutil_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetRepository) ProtoMessage() {}

func (x *ResponseGetRepository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetRepository.ProtoReflect.Descriptor instead.
func (*ResponseGetRepository) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseGetRepository) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,2,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_docutil_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{6}
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

type RequestGetPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetPage) Reset() {
	*x = RequestGetPage{}
	mi := &file_proto_docutil_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetPage) ProtoMessage() {}

func (x *RequestGetPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetPage.ProtoReflect.Descriptor instead.
func (*RequestGetPage) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{7}
}

func (x *RequestGetPage) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RequestGetPage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ResponseGetPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Doc           string                 `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	In            []*PageLink            `protobuf:"bytes,3,rep,name=in,proto3" json:"in,omitempty"`
	Out           []*PageLink            `protobuf:"bytes,4,rep,name=out,proto3" json:"out,omitempty"`
	RawUrl        string                 `protobuf:"bytes,5,opt,name=raw_url,json=rawUrl,proto3" json:"raw_url,omitempty"`
	EditUrl       string                 `protobuf:"bytes,6,opt,name=edit_url,json=editUrl,proto3" json:"edit_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetPage) Reset() {
	*x = ResponseGetPage{}
	mi := &file_proto_docutil_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetPage) ProtoMessage() {}

func (x *ResponseGetPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetPage.ProtoReflect.Descriptor instead.
func (*ResponseGetPage) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseGetPage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResponseGetPage) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *ResponseGetPage) GetIn() []*PageLink {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *ResponseGetPage) GetOut() []*PageLink {
	if x != nil {
		return x.Out
	}
	return nil
}

func (x *ResponseGetPage) GetRawUrl() string {
	if x != nil {
		return x.RawUrl
	}
	return ""
}

func (x *ResponseGetPage) GetEditUrl() string {
	if x != nil {
		return x.EditUrl
	}
	return ""
}

type PageLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LinkType               `protobuf:"varint,1,opt,name=type,proto3,enum=mono.docutil.LinkType" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Repository    string                 `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageLink) Reset() {
	*x = PageLink{}
	mi := &file_proto_docutil_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageLink) ProtoMessage() {}

func (x *PageLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageLink.ProtoReflect.Descriptor instead.
func (*PageLink) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{9}
}

func (x *PageLink) GetType() LinkType {
	if x != nil {
		return x.Type
	}
	return LinkType_LINK_TYPE_EXTERNAL
}

func (x *PageLink) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PageLink) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PageLink) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *PageLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RequestPageLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Sha           string                 `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPageLink) Reset() {
	*x = RequestPageLink{}
	mi := &file_proto_docutil_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPageLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPageLink) ProtoMessage() {}

func (x *RequestPageLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPageLink.ProtoReflect.Descriptor instead.
func (*RequestPageLink) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{10}
}

func (x *RequestPageLink) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RequestPageLink) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type ResponsePageLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            []*PageLink            `protobuf:"bytes,1,rep,name=in,proto3" json:"in,omitempty"`
	Out           []*PageLink            `protobuf:"bytes,2,rep,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePageLink) Reset() {
	*x = ResponsePageLink{}
	mi := &file_proto_docutil_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePageLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePageLink) ProtoMessage() {}

func (x *ResponsePageLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePageLink.ProtoReflect.Descriptor instead.
func (*ResponsePageLink) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{11}
}

func (x *ResponsePageLink) GetIn() []*PageLink {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *ResponsePageLink) GetOut() []*PageLink {
	if x != nil {
		return x.Out
	}
	return nil
}

type RequestGetDirectory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetDirectory) Reset() {
	*x = RequestGetDirectory{}
	mi := &file_proto_docutil_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetDirectory) ProtoMessage() {}

func (x *RequestGetDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetDirectory.ProtoReflect.Descriptor instead.
func (*RequestGetDirectory) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{12}
}

func (x *RequestGetDirectory) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RequestGetDirectory) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *RequestGetDirectory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ResponseGetDirectory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirectoryEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetDirectory) Reset() {
	*x = ResponseGetDirectory{}
	mi := &file_proto_docutil_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetDirectory) ProtoMessage() {}

func (x *ResponseGetDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetDirectory.ProtoReflect.Descriptor instead.
func (*ResponseGetDirectory) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseGetDirectory) GetEntries() []*DirectoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DirectoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_proto_docutil_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docutil_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryEntry.ProtoReflect.Descriptor instead.
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_docutil_search_proto_rawDescGZIP(), []int{14}
}

func (x *DirectoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectoryEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectoryEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

var File_proto_docutil_search_proto protoreflect.FileDescriptor

const file_proto_docutil_search_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/docutil/search.proto\x12\fmono.docutil\"\x1a\n" +
	"\x18RequestAvailableFeatures\"\xaa\x01\n" +
	"\x19ResponseAvailableFeatures\x12\x1b\n" +
	"\tpage_link\x18\x01 \x01(\bR\bpageLink\x12(\n" +
	"\x10full_text_search\x18\x02 \x01(\bR\x0efullTextSearch\x12F\n" +
	"\x13supported_file_type\x18\x03 \x03(\x0e2\x16.mono.docutil.FileTypeR\x11supportedFileType\"\x17\n" +
	"\x15RequestListRepository\"V\n" +
	"\x16ResponseListRepository\x12<\n" +
	"\frepositories\x18\x01 \x03(\v2\x18.mono.docutil.RepositoryR\frepositories\"*\n" +
	"\x14RequestGetRepository\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"Q\n" +
	"\x15ResponseGetRepository\x128\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x18.mono.docutil.RepositoryR\n" +
	"repository\"G\n" +
	"\n" +
	"Repository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0edefault_branch\x18\x02 \x01(\tR\rdefaultBranch\"8\n" +
	"\x0eRequestGetPage\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xbf\x01\n" +
	"\x0fResponseGetPage\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03doc\x18\x02 \x01(\tR\x03doc\x12&\n" +
	"\x02in\x18\x03 \x03(\v2\x16.mono.docutil.PageLinkR\x02in\x12(\n" +
	"\x03out\x18\x04 \x03(\v2\x16.mono.docutil.PageLinkR\x03out\x12\x17\n" +
	"\araw_url\x18\x05 \x01(\tR\x06rawUrl\x12\x19\n" +
	"\bedit_url\x18\x06 \x01(\tR\aeditUrl\"\xa6\x01\n" +
	"\bPageLink\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.mono.docutil.LinkTypeR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1e\n" +
	"\n" +
	"repository\x18\x04 \x01(\tR\n" +
	"repository\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\"7\n" +
	"\x0fRequestPageLink\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\"d\n" +
	"\x10ResponsePageLink\x12&\n" +
	"\x02in\x18\x01 \x03(\v2\x16.mono.docutil.PageLinkR\x02in\x12(\n" +
	"\x03out\x18\x02 \x03(\v2\x16.mono.docutil.PageLinkR\x03out\"O\n" +
	"\x13RequestGetDirectory\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"N\n" +
	"\x14ResponseGetDirectory\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.mono.docutil.DirectoryEntryR\aentries\"O\n" +
	"\x0eDirectoryEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir*\"\n" +
	"\bFileType\x12\x16\n" +
	"\x12FILE_TYPE_MARKDOWN\x10\x00*b\n" +
	"\bLinkType\x12\x16\n" +
	"\x12LINK_TYPE_EXTERNAL\x10\x00\x12\x1b\n" +
	"\x17LINK_TYPE_IN_REPOSITORY\x10\x01\x12!\n" +
	"\x1dLINK_TYPE_NEIGHBOR_REPOSITORY\x10\x022\x92\x04\n" +
	"\tDocSearch\x12d\n" +
	"\x11AvailableFeatures\x12&.mono.docutil.RequestAvailableFeatures\x1a'.mono.docutil.ResponseAvailableFeatures\x12[\n" +
	"\x0eListRepository\x12#.mono.docutil.RequestListRepository\x1a$.mono.docutil.ResponseListRepository\x12X\n" +
	"\rGetRepository\x12\".mono.docutil.RequestGetRepository\x1a#.mono.docutil.ResponseGetRepository\x12F\n" +
	"\aGetPage\x12\x1c.mono.docutil.RequestGetPage\x1a\x1d.mono.docutil.ResponseGetPage\x12I\n" +
	"\bPageLink\x12\x1d.mono.docutil.RequestPageLink\x1a\x1e.mono.docutil.ResponsePageLink\x12U\n" +
	"\fGetDirectory\x12!.mono.docutil.RequestGetDirectory\x1a\".mono.docutil.ResponseGetDirectoryB\x1dZ\x1bgo.f110.dev/mono/go/docutilb\x06proto3"

var (
	file_proto_docutil_search_proto_rawDescOnce sync.Once
	file_proto_docutil_search_proto_rawDescData []byte
)

func file_proto_docutil_search_proto_rawDescGZIP() []byte {
	file_proto_docutil_search_proto_rawDescOnce.Do(func() {
		file_proto_docutil_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docutil_search_proto_rawDesc), len(file_proto_docutil_search_proto_rawDesc)))
	})
	return file_proto_docutil_search_proto_rawDescData
}

var file_proto_docutil_search_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_docutil_search_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_docutil_search_proto_goTypes = []any{
	(FileType)(0),                     // 0: mono.docutil.FileType
	(LinkType)(0),                     // 1: mono.docutil.LinkType
	(*RequestAvailableFeatures)(nil),  // 2: mono.docutil.RequestAvailableFeatures
	(*ResponseAvailableFeatures)(nil), // 3: mono.docutil.ResponseAvailableFeatures
	(*RequestListRepository)(nil),     // 4: mono.docutil.RequestListRepository
	(*ResponseListRepository)(nil),    // 5: mono.docutil.ResponseListRepository
	(*RequestGetRepository)(nil),      // 6: mono.docutil.RequestGetRepository
	(*ResponseGetRepository)(nil),     // 7: mono.docutil.ResponseGetRepository
	(*Repository)(nil),                // 8: mono.docutil.Repository
	(*RequestGetPage)(nil),            // 9: mono.docutil.RequestGetPage
	(*ResponseGetPage)(nil),           // 10: mono.docutil.ResponseGetPage
	(*PageLink)(nil),                  // 11: mono.docutil.PageLink
	(*RequestPageLink)(nil),           // 12: mono.docutil.RequestPageLink
	(*ResponsePageLink)(nil),          // 13: mono.docutil.ResponsePageLink
	(*RequestGetDirectory)(nil),       // 14: mono.docutil.RequestGetDirectory
	(*ResponseGetDirectory)(nil),      // 15: mono.docutil.ResponseGetDirectory
	(*DirectoryEntry)(nil),            // 16: mono.docutil.DirectoryEntry
}
var file_proto_docutil_search_proto_depIdxs = []int32{
	0,  // 0: mono.docutil.ResponseAvailableFeatures.supported_file_type:type_name -> mono.docutil.FileType
	8,  // 1: mono.docutil.ResponseListRepository.repositories:type_name -> mono.docutil.Repository
	8,  // 2: mono.docutil.ResponseGetRepository.repository:type_name -> mono.docutil.Repository
	11, // 3: mono.docutil.ResponseGetPage.in:type_name -> mono.docutil.PageLink
	11, // 4: mono.docutil.ResponseGetPage.out:type_name -> mono.docutil.PageLink
	1,  // 5: mono.docutil.PageLink.type:type_name -> mono.docutil.LinkType
	11, // 6: mono.docutil.ResponsePageLink.in:type_name -> mono.docutil.PageLink
	11, // 7: mono.docutil.ResponsePageLink.out:type_name -> mono.docutil.PageLink
	16, // 8: mono.docutil.ResponseGetDirectory.entries:type_name -> mono.docutil.DirectoryEntry
	2,  // 9: mono.docutil.DocSearch.AvailableFeatures:input_type -> mono.docutil.RequestAvailableFeatures
	4,  // 10: mono.docutil.DocSearch.ListRepository:input_type -> mono.docutil.RequestListRepository
	6,  // 11: mono.docutil.DocSearch.GetRepository:input_type -> mono.docutil.RequestGetRepository
	9,  // 12: mono.docutil.DocSearch.GetPage:input_type -> mono.docutil.RequestGetPage
	12, // 13: mono.docutil.DocSearch.PageLink:input_type -> mono.docutil.RequestPageLink
	14, // 14: mono.docutil.DocSearch.GetDirectory:input_type -> mono.docutil.RequestGetDirectory
	3,  // 15: mono.docutil.DocSearch.AvailableFeatures:output_type -> mono.docutil.ResponseAvailableFeatures
	5,  // 16: mono.docutil.DocSearch.ListRepository:output_type -> mono.docutil.ResponseListRepository
	7,  // 17: mono.docutil.DocSearch.GetRepository:output_type -> mono.docutil.ResponseGetRepository
	10, // 18: mono.docutil.DocSearch.GetPage:output_type -> mono.docutil.ResponseGetPage
	13, // 19: mono.docutil.DocSearch.PageLink:output_type -> mono.docutil.ResponsePageLink
	15, // 20: mono.docutil.DocSearch.GetDirectory:output_type -> mono.docutil.ResponseGetDirectory
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_docutil_search_proto_init() }
func file_proto_docutil_search_proto_init() {
	if File_proto_docutil_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docutil_search_proto_rawDesc), len(file_proto_docutil_search_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_docutil_search_proto_goTypes,
		DependencyIndexes: file_proto_docutil_search_proto_depIdxs,
		EnumInfos:         file_proto_docutil_search_proto_enumTypes,
		MessageInfos:      file_proto_docutil_search_proto_msgTypes,
	}.Build()
	File_proto_docutil_search_proto = out.File
	file_proto_docutil_search_proto_goTypes = nil
	file_proto_docutil_search_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DocSearchClient is the client API for DocSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocSearchClient interface {
	AvailableFeatures(ctx context.Context, in *RequestAvailableFeatures, opts ...grpc.CallOption) (*ResponseAvailableFeatures, error)
	ListRepository(ctx context.Context, in *RequestListRepository, opts ...grpc.CallOption) (*ResponseListRepository, error)
	GetRepository(ctx context.Context, in *RequestGetRepository, opts ...grpc.CallOption) (*ResponseGetRepository, error)
	GetPage(ctx context.Context, in *RequestGetPage, opts ...grpc.CallOption) (*ResponseGetPage, error)
	PageLink(ctx context.Context, in *RequestPageLink, opts ...grpc.CallOption) (*ResponsePageLink, error)
	GetDirectory(ctx context.Context, in *RequestGetDirectory, opts ...grpc.CallOption) (*ResponseGetDirectory, error)
}

type docSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewDocSearchClient(cc grpc.ClientConnInterface) DocSearchClient {
	return &docSearchClient{cc}
}

func (c *docSearchClient) AvailableFeatures(ctx context.Context, in *RequestAvailableFeatures, opts ...grpc.CallOption) (*ResponseAvailableFeatures, error) {
	out := new(ResponseAvailableFeatures)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/AvailableFeatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docSearchClient) ListRepository(ctx context.Context, in *RequestListRepository, opts ...grpc.CallOption) (*ResponseListRepository, error) {
	out := new(ResponseListRepository)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/ListRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docSearchClient) GetRepository(ctx context.Context, in *RequestGetRepository, opts ...grpc.CallOption) (*ResponseGetRepository, error) {
	out := new(ResponseGetRepository)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/GetRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docSearchClient) GetPage(ctx context.Context, in *RequestGetPage, opts ...grpc.CallOption) (*ResponseGetPage, error) {
	out := new(ResponseGetPage)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docSearchClient) PageLink(ctx context.Context, in *RequestPageLink, opts ...grpc.CallOption) (*ResponsePageLink, error) {
	out := new(ResponsePageLink)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/PageLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docSearchClient) GetDirectory(ctx context.Context, in *RequestGetDirectory, opts ...grpc.CallOption) (*ResponseGetDirectory, error) {
	out := new(ResponseGetDirectory)
	err := c.cc.Invoke(ctx, "/mono.docutil.DocSearch/GetDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocSearchServer is the server API for DocSearch service.
type DocSearchServer interface {
	AvailableFeatures(context.Context, *RequestAvailableFeatures) (*ResponseAvailableFeatures, error)
	ListRepository(context.Context, *RequestListRepository) (*ResponseListRepository, error)
	GetRepository(context.Context, *RequestGetRepository) (*ResponseGetRepository, error)
	GetPage(context.Context, *RequestGetPage) (*ResponseGetPage, error)
	PageLink(context.Context, *RequestPageLink) (*ResponsePageLink, error)
	GetDirectory(context.Context, *RequestGetDirectory) (*ResponseGetDirectory, error)
}

// UnimplementedDocSearchServer can be embedded to have forward compatible implementations.
type UnimplementedDocSearchServer struct {
}

func (*UnimplementedDocSearchServer) AvailableFeatures(context.Context, *RequestAvailableFeatures) (*ResponseAvailableFeatures, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvailableFeatures not implemented")
}
func (*UnimplementedDocSearchServer) ListRepository(context.Context, *RequestListRepository) (*ResponseListRepository, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepository not implemented")
}
func (*UnimplementedDocSearchServer) GetRepository(context.Context, *RequestGetRepository) (*ResponseGetRepository, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepository not implemented")
}
func (*UnimplementedDocSearchServer) GetPage(context.Context, *RequestGetPage) (*ResponseGetPage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (*UnimplementedDocSearchServer) PageLink(context.Context, *RequestPageLink) (*ResponsePageLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageLink not implemented")
}
func (*UnimplementedDocSearchServer) GetDirectory(context.Context, *RequestGetDirectory) (*ResponseGetDirectory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectory not implemented")
}

func RegisterDocSearchServer(s *grpc.Server, srv DocSearchServer) {
	s.RegisterService(&_DocSearch_serviceDesc, srv)
}

func _DocSearch_AvailableFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAvailableFeatures)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).AvailableFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/AvailableFeatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).AvailableFeatures(ctx, req.(*RequestAvailableFeatures))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocSearch_ListRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestListRepository)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).ListRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/ListRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).ListRepository(ctx, req.(*RequestListRepository))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocSearch_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetRepository)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/GetRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).GetRepository(ctx, req.(*RequestGetRepository))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocSearch_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetPage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).GetPage(ctx, req.(*RequestGetPage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocSearch_PageLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPageLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).PageLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/PageLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).PageLink(ctx, req.(*RequestPageLink))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocSearch_GetDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetDirectory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocSearchServer).GetDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mono.docutil.DocSearch/GetDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocSearchServer).GetDirectory(ctx, req.(*RequestGetDirectory))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocSearch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mono.docutil.DocSearch",
	HandlerType: (*DocSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvailableFeatures",
			Handler:    _DocSearch_AvailableFeatures_Handler,
		},
		{
			MethodName: "ListRepository",
			Handler:    _DocSearch_ListRepository_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _DocSearch_GetRepository_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _DocSearch_GetPage_Handler,
		},
		{
			MethodName: "PageLink",
			Handler:    _DocSearch_PageLink_Handler,
		},
		{
			MethodName: "GetDirectory",
			Handler:    _DocSearch_GetDirectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/docutil/search.proto",
}
